dist: xenial
language: cpp
sudo: true
os: linux
cache:
  apt: true

# for meson
python:
- '3.6'

matrix:
  include:
    - env: COMPILER_CXX=g++-8 COMPILER_CC=gcc-8 BUILD=Debug
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - gcc-8
            - boost1.67
            - ninja-build
            - python3-pip
            - python3-setuptools
            - libunbound-dev
            - openssl

before_script:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then export CXX=${COMPILER_CXX}; export CC=${COMPILER_CC}; fi
  - sudo pip3 install meson
  - pushd benchmarks/ovs/
  - bash ovs_prepare.sh
  - popd
  - mkdir build
  - meson build
  - cd build
  - meson configure -Dovs_test_app=true

script: ninja && ninja test

after_success:
  - cat meson-logs/testlog.txt
 
