dist: focal
language: cpp
sudo: true
os: linux
cache:
  apt: true

# for meson
python:
- '3.7'

matrix:
  include:
    - env: BUILD=Debug
      compiler: gcc
      addons:
        apt:
          packages:
            - libboost-all-dev
            - ninja-build
            - python3-pip
            - python3-setuptools
            - libunbound-dev
            - openssl

before_script:
  - sudo pip3 install meson
  - pushd benchmarks/ovs/
  - bash ovs_prepare.sh
  - popd
  - mkdir build
  - meson build
  - cd build
  - meson configure -Dovs_test_app=true

script: ninja && ninja test

after_success:
  - cat meson-logs/testlog.txt
 
